// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

// movies
export const MOVIES_REQUEST = 'MOVIES_REQUEST';
export const MOVIES_RESPONSE = 'MOVIES_RESPONSE';
export const MOVIES_FAILED = 'MOVIES_FAILED';
export const MOVIES_ENABLE_LOADER = 'MOVIES_ENABLE_LOADER';
export const MOVIES_DISABLE_LOADER = 'MOVIES_DISABLE_LOADER';